### ISSUE TITLE
How to install and use this UI library?

### ISSUE THREAD

**Issue by hanpanpan200** [tipsi/tipsi-ui-kit#12]
Hi when I'm trying to use the `<Expand>` component, I use
```
yarn add tipsi-ui-kit
```

and then added:
```
import { Expand } from 'tipsi-ui-kit'
```

but I got the error below:
[error](https://www.dropbox.com/s/l5e02d302eykug4/1.jpeg?dl=0)

And I can't find any instruction for how to install the lib.

Anyone can help me?

**Comment by isnifer** [comment]
@hanpanpan200 Hi! Thank you for your issue. We have updated our library on npm. Now you can use it without errors :)

**Comment by isnifer** [comment]
@hanpanpan200 current version is 0.1.1
